In [1]:
import numpy as np

In [2]:
np.__version__

'1.21.5'

In [3]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [4]:
z=np.zeros(10)
z[4]=1
print(z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [5]:
v = np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [6]:
a=np.arange(15)
a[::-1]

array([14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

In [7]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [9]:
np.nonzero([1,2,0,0,4,0])

(array([0, 1, 4], dtype=int64),)

In [12]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [15]:
np.random.random((3,3,3))

array([[[0.90918896, 0.95470116, 0.10113665],
        [0.4192393 , 0.51059702, 0.04207679],
        [0.72497264, 0.53034105, 0.69736227]],

       [[0.68371142, 0.98467141, 0.17578269],
        [0.00907442, 0.52889151, 0.35683675],
        [0.86410438, 0.51168709, 0.00664362]],

       [[0.85707836, 0.95539401, 0.3030831 ],
        [0.85712396, 0.40796277, 0.4677045 ],
        [0.0237235 , 0.10167326, 0.59684758]]])

In [21]:
a = np.random.random((10,10))
zmin,zmax=a.min(),a.max()
zmin,zmax

(0.01564134869492051, 0.9910641467779717)

In [23]:
z=np.random.random(30)
z.mean()

0.5934213565633548

In [26]:
z=np.ones((10,10))
z[1:-1,1:-1]=0
z

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [28]:
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
0.3 == 3 * 0.1 

False

In [34]:
np.diag(1+np.arange(4),k=-1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

In [43]:
np.ones((8,8))

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

In [46]:
Z = np.zeros((8,8),dtype=int) 
Z[1::2,::2] = 1 
Z[::2,1::2] = 1
print(z)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [48]:
np.unravel_index(100,(6,7,8))

(1, 5, 4)

In [52]:
np.tile(np.array([[0,1],[1,0]]),(4,4))

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [53]:
a=np.random.random((5,5))
amax,amin=a.max(),a.min()
a=(a-amin)/(amax-amin)
print(a)

[[0.47985802 0.97461651 0.00637999 0.67256148 0.19117472]
 [0.75731601 0.00894675 0.67473431 0.51520582 0.03908436]
 [0.62898061 0.29161196 0.11145874 0.21197836 0.29726442]
 [1.         0.         0.76189891 0.42308149 0.92395049]
 [0.25608057 0.79804157 0.98362987 0.66279809 0.82452524]]


In [9]:
color=np.dtype([("r",np.ubyte,1),
               ("g",np.ubyte,1),
               ("b",np.ubyte,1),
               ("a",np.ubyte,1)])
color

C:\Users\Admin\AppData\Local\Temp\ipykernel_8720\1899958890.py:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  color=np.dtype([("r",np.ubyte,1),


dtype([('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

In [56]:
Z = np.dot(np.ones((5,3)),np.ones((3,2))) 
print(Z) 

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


In [57]:
Z = np.arange(11) 
Z[(3 < Z) & (Z <= 8)] *= -1 
z

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [2]:
sum(range(5),-1)

9

In [ ]:
#25.	Consider an integer vector Z, which of these expressions are legal?
Z**Z 
2 << Z >> 2 
Z<- Z 
1j*Z 
Z/1/1 
Z<Z>Z 
ans: No

In [ ]:
np.array(0) // np.array(0.)
np.array(0) / np.array(0)
np.array(0) / np.array(0.) 
ans: nan

In [8]:
Z= np.random.uniform(-10,+10,10)
print(np.trunc(Z + np.copysign(0.5, Z))) 

[ -6.   7.  -7.   1.   8.  -1. -10.   4.   8.  -4.]


In [10]:
Z = np.random.uniform(0,10,10) 
print (Z - Z%1)
print (np.floor(Z))
print (np.ceil(Z)-1)
print (Z.astype(int))
print (np.trunc(Z)) 

[4. 0. 6. 7. 7. 1. 1. 2. 7. 1.]
[4. 0. 6. 7. 7. 1. 1. 2. 7. 1.]
[4. 0. 6. 7. 7. 1. 1. 2. 7. 1.]
[4 0 6 7 7 1 1 2 7 1]
[4. 0. 6. 7. 7. 1. 1. 2. 7. 1.]


In [17]:
z = np.zeros((5,5))
z += np.arange(5)
print(z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


In [21]:
def generate():
    for x in range(10):
        yield x
z = np.fromiter(generate(),dtype=float,count=-1)
print(z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [22]:
Z= np.linspace(0,1,12,endpoint=True)[1:-1]
print(Z)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


In [23]:
a=np.random.random(10)
a.sort()
print(a)

[0.08926727 0.27545738 0.27645018 0.51016732 0.56509885 0.59912111
 0.72800273 0.84994064 0.97771613 0.99164208]


In [25]:
Z= np.arange(10)
np.add.reduce(Z)

45

In [27]:
a=np.random.randint(0,2,5)
b=np.random.randint(0,2,5)
equal=np.allclose(a,b)
equal

False

In [ ]:
35.Make an array immutable (read-only) 
z = np.zeros(10)
z.flags.writeable = False
z[0] = 1
z

In [32]:
Z = np.random.random((10,2)) 
X,Y = Z[:,0], Z[:,1] 
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)
print(R)
print(T) 

[0.42023109 0.96848749 1.09110071 0.69157882 0.71510727 0.86904086
 0.25192628 0.65537121 0.80606698 0.7795356 ]
[1.54226208 0.64569208 0.91307943 1.12536165 1.13314302 1.38609383
 0.22868169 1.19951164 1.38235943 1.50741836]


In [33]:
Z= np.random.random(10)
Z[Z.argmax()] = 0
print(Z) 

[0.0766121  0.         0.34272417 0.07352062 0.27913364 0.04928233
 0.1059214  0.13748547 0.18828419 0.34644388]


In [38]:
z= np.zeros((10,10), [('x',float),('y',float)])
z['x'],z['y'] = np.meshgrid(np.linspace(0,1,10),
np.linspace(0,1,10))
print(z) 

[[(0.        , 0.        ) (0.11111111, 0.        )
  (0.22222222, 0.        ) (0.33333333, 0.        )
  (0.44444444, 0.        ) (0.55555556, 0.        )
  (0.66666667, 0.        ) (0.77777778, 0.        )
  (0.88888889, 0.        ) (1.        , 0.        )]
 [(0.        , 0.11111111) (0.11111111, 0.11111111)
  (0.22222222, 0.11111111) (0.33333333, 0.11111111)
  (0.44444444, 0.11111111) (0.55555556, 0.11111111)
  (0.66666667, 0.11111111) (0.77777778, 0.11111111)
  (0.88888889, 0.11111111) (1.        , 0.11111111)]
 [(0.        , 0.22222222) (0.11111111, 0.22222222)
  (0.22222222, 0.22222222) (0.33333333, 0.22222222)
  (0.44444444, 0.22222222) (0.55555556, 0.22222222)
  (0.66666667, 0.22222222) (0.77777778, 0.22222222)
  (0.88888889, 0.22222222) (1.        , 0.22222222)]
 [(0.        , 0.33333333) (0.11111111, 0.33333333)
  (0.22222222, 0.33333333) (0.33333333, 0.33333333)
  (0.44444444, 0.33333333) (0.55555556, 0.33333333)
  (0.66666667, 0.33333333) (0.77777778, 0.33333333)
  (0.8888

In [39]:
X= np.arange(8) 
Y= X + 0.5 
C = 1.0 / np.subtract.outer(X, Y)
print(np.linalg.det(C))

3638.1636371179666


In [41]:
for dtype in [np.int8, np.int32, np.int64]: 
    print(np.iinfo(dtype).min)
    print(np.iinfo(dtype).max) 
for dtype in [np.float32, np.float64]:
    print(np.finfo(dtype).min)
    print(np.finfo(dtype).max)
    print(np.finfo(dtype).eps) 

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


In [1]:
import numpy as np

In [6]:
np.set_printoptions(threshold=True) 
Z = np.zeros((25,25))
print(Z) 

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [ ]:
z = np.arange(100)
v=np.random.uniform