In [1]:
import numpy as np

In [2]:
np.__version__

'1.24.4'

In [ ]:
# if you want to change the version
# To upgrade: pip install numpy --upgrade
# To degrade: python -m pip install numpy == name of version

In [3]:
np.array(range(10))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
np.array([3,4,5,6],dtype=float)

array([3., 4., 5., 6.])

In [5]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
#numpy is used for create N dimentional arrays

In [10]:
a = np.array([3,4])
ab

array([3, 4])

In [11]:
a.ndim

1

In [7]:
a = np.array([[3,4],[5,6]])
a.ndim

2

In [8]:
a

array([[3, 4],
       [5, 6]])

In [9]:
a = np.array([[[3,4]],[[5,6]]])
a.ndim

3

In [10]:
a

array([[[3, 4]],

       [[5, 6]]])

In [12]:
a.shape

(2,)

In [13]:
a.dtype

dtype('int32')

In [14]:
a.size

2

In [20]:
np.add(25,4)

29

In [23]:
a

array([3, 4])

In [26]:
b = np.arange(9).reshape((3,3))
b

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [28]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [29]:
np.eye(5,k=2,dtype='int')

array([[0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [2]:
np.eye(5,k=1)

array([[0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0.]])

In [3]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
#random number generation we use random from numpy
#return random float in open half interval(0.0,1.0)
np.random.random(5)

array([0.66552658, 0.77251181, 0.17763594, 0.07872085, 0.23050432])

In [24]:
np.random.random((3,3))

array([[0.011214  , 0.43816548, 0.14109083],
       [0.18018591, 0.85696553, 0.85670225],
       [0.56854823, 0.37871566, 0.06915676]])

In [4]:
np.random.randint(50,100,100)

array([64, 89, 87, 73, 78, 94, 99, 50, 82, 99, 57, 82, 78, 98, 60, 80, 69,
       92, 64, 59, 63, 95, 71, 73, 81, 93, 50, 83, 86, 65, 65, 85, 91, 80,
       85, 61, 81, 95, 96, 93, 86, 95, 54, 86, 72, 96, 92, 79, 53, 85, 64,
       73, 90, 57, 90, 69, 72, 92, 84, 83, 63, 62, 57, 99, 77, 74, 66, 75,
       57, 51, 78, 77, 59, 65, 89, 95, 56, 64, 70, 92, 75, 77, 51, 58, 97,
       89, 50, 71, 77, 97, 57, 62, 65, 90, 58, 82, 73, 69, 91, 79])

In [7]:
np.linspace(50,70,20,dtype = int)

array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66,
       67, 68, 70])

In [18]:
# start stop and equal space
np.linspace(1,20,10)

array([ 1.        ,  3.11111111,  5.22222222,  7.33333333,  9.44444444,
       11.55555556, 13.66666667, 15.77777778, 17.88888889, 20.        ])

In [20]:
np.linspace(1,20,10,dtype=int)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 20])

In [31]:
a = np.arange(12).reshape((3,4))

In [32]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [20]:
b = np.arange(24).reshape(6,4)

In [21]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [22]:
b[0]

array([0, 1, 2, 3])

In [23]:
b[::2]

array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11],
       [16, 17, 18, 19]])

In [24]:
b[::-1,::-1]

array([[23, 22, 21, 20],
       [19, 18, 17, 16],
       [15, 14, 13, 12],
       [11, 10,  9,  8],
       [ 7,  6,  5,  4],
       [ 3,  2,  1,  0]])

In [36]:
b.shape

(6, 4)

In [40]:
b[::5,::3] = [[0,0],
              [0,0]]

In [41]:
b

array([[ 0,  1,  2,  0],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [ 0, 21, 22,  0]])

In [42]:
b[::5,::3]

array([[0, 0],
       [0, 0]])

In [43]:
np.zeros_like(b)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [46]:
np.empty_like(a)

array([[4128860, 6029375, 3801155, 5570652],
       [6619251, 7536754, 4259932, 7143524],
       [7209065, 4259932, 7340144, 6357060]])

In [48]:
c = np.arange(20)

In [49]:
c

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [53]:
np.zeros([2,2])

array([[0., 0.],
       [0., 0.]])

In [12]:
np.full(4,fill_value=1)

array([1, 1, 1, 1])

In [13]:
np.full((4,5),fill_value=1)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [68]:
d = np.arange(1,12)

In [69]:
d

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [16]:
np.arange(2,20,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [17]:
np.sum(np.arange(2,20,2))

90

In [70]:
d[::-1]

array([11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [71]:
d[::-2]

array([11,  9,  7,  5,  3,  1])

In [74]:
d>5

array([False, False, False, False, False,  True,  True,  True,  True,
        True,  True])

In [75]:
d[d>5]

array([ 6,  7,  8,  9, 10, 11])

In [34]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [37]:
a.sum(axis=1,keepdims=True)

array([[ 6],
       [22],
       [38]])

In [44]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [38]:
a.sum(axis=0,keepdims=True)

array([[12, 15, 18, 21]])

In [39]:
a.mean(axis=1,dtype='int')

array([1, 5, 9])

In [43]:
np.median(a,axis=1, out=None, overwrite_input=True, keepdims=True)

array([[1.5],
       [5.5],
       [9.5]])

In [49]:
np.percentile(a,100,axis=1,overwrite_input=False,
    interpolation='higher',
    keepdims=True)

array([[ 3],
       [ 7],
       [11]])

In [60]:
np.mod(a,5)# mod = %reminder

array([[0, 1, 2, 3],
       [4, 0, 1, 2],
       [3, 4, 0, 1]], dtype=int32)

In [61]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [62]:
np.power(a,2)

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]], dtype=int32)

In [66]:
np.divide(a,2)

array([[0. , 0.5, 1. , 1.5],
       [2. , 2.5, 3. , 3.5],
       [4. , 4.5, 5. , 5.5]])

In [67]:
np.multiply(a,7)

array([[ 0,  7, 14, 21],
       [28, 35, 42, 49],
       [56, 63, 70, 77]])

In [68]:
np.floor_divide(a,2)

array([[0, 0, 1, 1],
       [2, 2, 3, 3],
       [4, 4, 5, 5]], dtype=int32)

In [54]:
np.std(a,axis=1)

array([1.11803399, 1.11803399, 1.11803399])

In [56]:
c = np.array((2,2))
c

array([2, 2])

In [57]:
d = np.array((2,2))
d

array([2, 2])

In [58]:
np.add(c,d)

array([4, 4])

In [59]:
np.add(c,1200)

array([1202, 1202])

In [70]:
#diagonal element are 1 and remaining are 0
m = np.identity(4)
m

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [71]:
np.add(m,5)

array([[6., 5., 5., 5.],
       [5., 6., 5., 5.],
       [5., 5., 6., 5.],
       [5., 5., 5., 6.]])

In [72]:
np.multiply(m,3)

array([[3., 0., 0., 0.],
       [0., 3., 0., 0.],
       [0., 0., 3., 0.],
       [0., 0., 0., 3.]])

In [73]:
np.power(m,2)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### Versions of libraries

In [8]:
import numpy

In [9]:
numpy.__version__

'1.21.5'

In [10]:
import matplotlib

In [11]:
matplotlib.__version__

'3.5.2'

In [12]:
import pandas

In [13]:
pandas.__version__

'1.4.4'

In [14]:
import seaborn

In [15]:
seaborn.__version__

'0.11.2'